### PR TITLE
Enable test checking by default

### PR DESCRIPTION
**Pull request by CameronDiver**
Change-type: major
Signed-off-by: Cameron Diver <cameron@balena.io>

### CODE REVIEW

**Comment by roman-mazur** [comment]
The lint check finds the `.only` in the code, and it was activated with a dedicated parameter because you most likely don't want to run it for the main codebase, but only for the test files.

**Comment by CameronDiver** [comment]
My only thoughts was that this requires an explicit lint command added for test files, and I think it's safe to assume that extremely few codebases will have `describe.only` or `it.only` intentionally.

This just moves the work to this module, than once in every module which should implement this.

**Comment by roman-mazur** [comment]
@CameronDiver is it possible to modify package.json file of the project that add our linter as a dependency (maybe from the `build` script)? In this case, we can set all the necessary setup automatically.

This change does make the setup a bit shorter but still requires the setup.

**Comment by CameronDiver** [comment]
I'm not entirely sure what you mean @roman-mazur , how would this look?

**Comment by Page-** [comment]
I'd rather have the explicit flag as this check only makes sense for tests and it leaves the option for more test specific checks that might be found in the main codebase, or alternatively disabling certain checks for tests (I think an any in tests is far more acceptable and often required in order to explicitly test behavior of typings are ignored, eg a downstream js project consuming a typescript module)

**Comment by CameronDiver** [comment]
@Page- You do make a great point about different levels of lint being acceptable in tests and therefore a separate command being worth it. I'll close out this PR.

**Comment by roman-mazur** [comment]
@CameronDiver what I mean is that you run
```
npm i --save-dev @balena/lint
```
And your package.json is also updated to include
```json
{
  "scripts": {
    "lint": "balena-lint ..."
  },
  "husky": {
    "hooks": { "pre-commit": "lint-staged" }
  },
  "lint-staged": {
    "*.ts": {  },
    "test/**/*.ts": { }
   }
}
```

**Pull request closed without merging**
